clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: epoetry-client

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - COMPOSERVER=--2
      - DOCUMENT_ROOT=/test/oe_content

pipeline:
  composer-install-lowest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer self-update --2
      - composer update --prefer-lowest --prefer-stable --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer self-update --2
      - composer install --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit

matrix:
  include:
    - { PHP_VERSION: 7.4, COMPOSER_BOUNDARY: lowest, TYPE: phpunit }
    - { PHP_VERSION: 8.0, COMPOSER_BOUNDARY: lowest, TYPE: phpunit }

    - { PHP_VERSION: 7.4, COMPOSER_BOUNDARY: highest, TYPE: phpunit }
    - { PHP_VERSION: 8.0, COMPOSER_BOUNDARY: highest, TYPE: phpunit }
