services:
  _defaults:
    autowire: true
    autoconfigure: true

  OpenEuropa\EPoetry\:
    resource: '../../src'

  Symfony\Component\Console\Application:
    # Set to public so we can get it from container in bin file
    # via "$container->get(Application::class)"
    public: true

  Psr\Log\LoggerInterface: "@logger"

  logger:
    class: \Monolog\Logger
    arguments:
      $name: "epoetry"
