services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Log\LoggerInterface: "@logger"
  Symfony\Component\Serializer\SerializerInterface: "@serializer"

  OpenEuropa\EPoetry\:
    resource: '../../src'

  Symfony\Component\Console\Application:
    # Set to public so we can get it from container in bin file
    # via "$container->get(Application::class)"
    public: true
    calls:
      - setDispatcher: [ "@event_dispatcher"]

  serializer:
    class: \OpenEuropa\EPoetry\Serializer\Serializer

  console_handler:
    class: \Symfony\Bridge\Monolog\Handler\ConsoleHandler
    tags:
        - { name: kernel.event_subscriber }

  event_dispatcher:
    class: \Symfony\Component\EventDispatcher\EventDispatcher

  logger:
    class: \Monolog\Logger
    arguments:
      $name: "epoetry"
    calls:
      - setHandlers:
        - [ "@console_handler" ]