OpenEuropa\EPoetry\Notification\Type\ReceiveNotification:
    properties:
        notification:
            -   Valid: ~
            -   NotNull: ~

OpenEuropa\EPoetry\Notification\Type\DgtNotification:
    constraints:
        -   OpenEuropa\EPoetry\Validation\Constraints\DgtNotificationConstraint: ~

    properties:
        notificationType:
            -   NotBlank: ~
            -   Choice:
                    choices: [ RequestStatusChange, ProductStatusChange, ProductDelivery, CorrectionStatusChange ]
                    message: |
                        Choose a valid notification type:
                        - RequestStatusChange
                        - ProductStatusChange
                        - ProductDelivery
                        - CorrectionStatusChange
        linguisticRequest:
            -   Valid: ~

OpenEuropa\EPoetry\Notification\Type\LinguisticRequest:
    properties:
        status:
            -   Choice:
                    choices: [ Accepted, Rejected, Executed, Suspended, Cancelled, Validated ]
                    message: |
                        Choose a valid linguistic request status.
        requestReference:
            -   Valid: ~

OpenEuropa\EPoetry\Notification\Type\RequestReference:
    properties:
        year:
            -   NotBlank: ~
        number:
            -   NotBlank: ~
        part:
            -   NotBlank: ~
        version:
            -   NotBlank: ~
