OpenEuropa\EPoetry\Notification\Type\ReceiveNotification:
    properties:
        notification:
            -   Valid: ~
            -   NotNull: ~

OpenEuropa\EPoetry\Notification\Type\DgtNotification:
    constraints:
        -   OpenEuropa\EPoetry\Validation\Constraints\DgtNotificationConstraint: ~

    properties:
        notificationType:
            -   NotBlank: ~
            -   Choice:
                    choices: [ RequestStatusChange, ProductStatusChange, ProductDelivery, CorrectionStatusChange ]
                    message: |
                        Choose a valid notification type:
                        - RequestStatusChange
                        - ProductStatusChange
                        - ProductDelivery
                        - CorrectionStatusChange
        linguisticRequest:
            -   Valid: ~
        product:
            -   Valid: ~

OpenEuropa\EPoetry\Notification\Type\LinguisticRequest:
    properties:
        status:
            -   Choice:
                    choices: [ Accepted, Rejected, Executed, Suspended, Cancelled, Validated ]
                    message: |
                        Choose a valid linguistic request status:
                        - Accepted
                        - Rejected
                        - Executed
                        - Suspended
                        - Cancelled
                        - Validated
        requestReference:
            -   Valid: ~

OpenEuropa\EPoetry\Notification\Type\RequestReference:
    properties:
        year:
            -   NotBlank: ~
            -   Regex: '/^20\d{2}$/'
        number:
            -   NotBlank: ~
            -   PositiveOrZero: ~
        part:
            -   NotBlank: ~
            -   PositiveOrZero: ~
        version:
            -   NotBlank: ~
            -   PositiveOrZero: ~
        productType:
            -   Choice:
                    choices: [ TRA, EDT, RSE, RSO, SPO ]
                    message: |
                        Choose a valid "productType":
                        - TRA
                        - EDT
                        - RSE
                        - RSO
                        - SPO

OpenEuropa\EPoetry\Notification\Type\Product:
    constraints:
        -   OpenEuropa\EPoetry\Validation\Constraints\ProductConstraint: ~

    properties:
        productReference:
            -   Valid: ~
        status:
            -   Choice:
                    choices: [ Accepted, Closed, Ongoing, ReadyToBeSent, Suspended, Cancelled, Sent, Rejected, Requested, Invalid ]
                    message: |
                        Choose a valid product status:
                        - Accepted
                        - Closed
                        - Ongoing
                        - ReadyToBeSent
                        - Suspended
                        - Cancelled
                        - Sent
                        - Rejected
                        - Requested
                        - Invalid
        format:
            -   Choice:
                    choices: [ XLS, XLSX, DOC, DOCX, PPTX, PPT, HTM, HTML, RTF, VSD, PDF, TIF, ZIP, TIFF, TXT, XML, XMW ]
                    message: |
                        Choose a valid file format:
                        - XLS
                        - XLSX
                        - DOC
                        - DOCX
                        - PPTX
                        - PPT
                        - HTM
                        - HTML
                        - RTF
                        - VSD
                        - PDF
                        - TIF
                        - ZIP
                        - TIFF
                        - TXT
                        - XML
                        - XMW

OpenEuropa\EPoetry\Notification\Type\ProductReference:
    properties:
        requestReference:
            -   Valid: ~
