OpenEuropa\EPoetry\Request\Type\CreateLinguisticRequest:
    properties:
        requestDetails:
            - Valid: ~
            - NotNull: ~
        applicationName:
            - NotBlank: ~
        templateName:
            - NotBlank: ~
            - Choice:
                choices: [ DEFAULT, WEBTRA, HOTL, EDT, WEBEDT, RSE, RSO, SPO, PP, QE ]
                message: |
                    Choose a valid template name
                    - DEFAULT for full length translation
                    - WEBTRA for web translation
                    - HOTL for hotline
                    - EDT	for standard editing
                    - WEBEDT for web editing
                    - RSE for written summary
                    - RSO for oral summary
                    - SPO for spotcheck
                    - PP for spokesperson's service press documents
                    - QE for replies to MEPs’ written questions

OpenEuropa\EPoetry\Request\Type\RequestDetailsIn:
    properties:
        title:
            - Length:
                min: 1
                max: 500
                allowEmptyString: false
        internalReference:
            - Length:
                min: 0
                max: 100
        destination:
            - Choice:
                choices: [ EM, EXT, IE, INTERNE, JO, PUBLIC ]
                message: |
                    Choose a valid destination value
                    - EM for Member State
                    - EXT for Citizen/Company
                    - IE for European Institutions
                    - INTERNE for Internal
                    - JO for Official Journal
                    - PUBLIC for Public
