OpenEuropa\EPoetry\Request\Type\CreateLinguisticRequest:
    constraints:
        -   OpenEuropa\EPoetry\Validation\Constraints\CreateLinguisticRequestConstraint: ~

    properties:
        requestDetails:
            - Valid: ~
            - NotNull: ~
        applicationName:
            - NotBlank: ~
        templateName:
            - NotBlank: ~
            - Choice:
                choices: [ DEFAULT, WEBTRA, HOTL, EDT, WEBEDT, RSE, RSO, SPO, PP, QE ]
                message: |
                    Choose a valid template name
                    - DEFAULT for full length translation
                    - WEBTRA for web translation
                    - HOTL for hotline
                    - EDT for standard editing
                    - WEBEDT for web editing
                    - RSE for written summary
                    - RSO for oral summary
                    - SPO for spotcheck
                    - PP for spokesperson's service press documents
                    - QE for replies to MEPs’ written questions

OpenEuropa\EPoetry\Request\Type\ResubmitRequest:
    constraints:
        -   OpenEuropa\EPoetry\Validation\Constraints\ResubmitRequestConstraint: ~

    properties:
        resubmitRequest:
            - Valid: ~
            - NotNull: ~
        applicationName:
            - NotBlank: ~
        templateName:
            - NotBlank: ~
            - Choice:
                  choices: [ DEFAULT, WEBTRA, HOTL, EDT, WEBEDT, RSE, RSO, SPO, PP, QE ]
                  message: |
                      Choose a valid template name
                      - DEFAULT for full length translation
                      - WEBTRA for web translation
                      - HOTL for hotline
                      - EDT for standard editing
                      - WEBEDT for web editing
                      - RSE for written summary
                      - RSO for oral summary
                      - SPO for spotcheck
                      - PP for spokesperson's service press documents
                      - QE for replies to MEPs’ written questions

OpenEuropa\EPoetry\Request\Type\ModifyLinguisticRequest:
    properties:
        modifyLinguisticRequest:
            - Valid: ~
            - NotNull: ~
        applicationName:
            - NotBlank: ~

OpenEuropa\EPoetry\Request\Type\RequestDetailsIn:
    constraints:
        - OpenEuropa\EPoetry\Validation\Constraints\RequestDetailsInConstraint: ~

    properties:
        title:
            - Length:
                min: 1
                max: 500
                allowEmptyString: false
            - NotNull: ~
        workflowCode:
            - Choice:
                choices: [ '', WEB, HOTL, STS, PP, QE ]
                message: |
                    Choose a valid workflow code or set empty value
                    - WEB
                    - HOTL
                    - STS
                    - PP
                    - QE
        internalReference:
            - Length:
                min: 0
                max: 100
        comment:
            - Length:
                min: 0
                max: 1700
        accessibleTo:
            - Choice:
                choices: [ CONTACTS, UNIT, DIR, DG, ON_BEHALF_DG ]
                message: |
                    Choose a valid accessible to value
                    - CONTACTS
                    - UNIT only for proxy authenticated systems
                    - DIR only for proxy authenticated systems
                    - DG
                    - ON_BEHALF_DG
        keyword1:
            - Length:
                min: 0
                max: 100
        keyword2:
            - Length:
                  min: 0
                  max: 100
        keyword3:
            - Length:
                  min: 0
                  max: 100
        products:
            - Valid: ~
            - NotNull: ~
        contacts:
            - Valid: ~
            - NotNull: ~
        auxiliaryDocuments:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\Products:
    properties:
        product:
            - Valid: ~
            - NotNull: ~

OpenEuropa\EPoetry\Request\Type\ModifyProductRequestIn:
    properties:
        language:
            - NotBlank: ~
        requestedDeadline:
            - NotNull: ~
        trackChanges:
            - NotNull: ~
            - Type: bool

OpenEuropa\EPoetry\Request\Type\ProductRequestIn:
    properties:
        language:
            - NotBlank: ~
        requestedDeadline:
            - NotNull: ~
        trackChanges:
            - NotNull: ~
            - Type: bool

OpenEuropa\EPoetry\Request\Type\Contacts:
    properties:
        contact:
            - Valid: ~
            - NotNull: ~

OpenEuropa\EPoetry\Request\Type\ContactPersonIn:
    properties:
        userId:
            - NotBlank: ~
        contactRole:
            - NotBlank: ~

OpenEuropa\EPoetry\Request\Type\AuxiliaryDocumentsIn:
    properties:
        referenceDocuments:
            - Valid: ~
        traxDocuments:
            - Valid: ~
        srcDocument:
            - Valid: ~
        spotDocument:
            - Valid: ~
        prtDocuments:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\SrcDocumentIn:
    properties:
        fileName:
            - NotBlank: ~
        content:
            - NotBlank: ~
        comment:
            - Length:
                min: 0
                max: 500

OpenEuropa\EPoetry\Request\Type\ReferenceDocuments:
    properties:
        document:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\TraxDocuments:
    properties:
        document:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\PrtDocuments:
    properties:
        document:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\DocumentIn:
    properties:
        fileName:
            - NotBlank: ~
        content:
            - NotBlank: ~
        comment:
            - Length:
                  min: 0
                  max: 500

OpenEuropa\EPoetry\Request\Type\DossierReference:
    properties:
        requesterCode:
            - Length:
                  min: 0
                  max: 500
        number:
            - PositiveOrZero: ~
        year:
            - DateTime:
                  format: Y

OpenEuropa\EPoetry\Request\Type\RequestReferenceIn:
    properties:
        dossier:
            - Valid: ~
            - NotNull: ~
        productType:
            - NotBlank: ~
            - Choice:
                  choices: [ ERR, EXT, EDT, TRA, RSO, RSE, REV, PER, SPO ]
                  message: |
                      Choose a valid product type
                      - ERR
                      - EXT
                      - EDT
                      - TRA
                      - RSO
                      - RSE
                      - REV
                      - PER
                      - SPO
        part:
            - PositiveOrZero: ~

OpenEuropa\EPoetry\Request\Type\LinguisticRequestIn:
    properties:
        requestDetails:
            - Valid: ~
            - NotNull: ~
        requestReference:
            - Valid: ~
            - NotNull: ~

OpenEuropa\EPoetry\Request\Type\ModifyRequestDetailsIn:
    properties:
        requestReference:
            - Valid: ~
        requestDetails:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\ModifyRequestReferenceIn:
    properties:
        dossier:
            - Valid: ~
        productType:
            - Choice:
                  choices: [ ERR, EXT, EDT, TRA, RSO, RSE, REV, PER, SPO ]
                  message: |
                      Choose a valid product type
                      - ERR
                      - EXT
                      - EDT
                      - TRA
                      - RSO
                      - RSE
                      - REV
                      - PER
                      - SPO
        part:
            - PositiveOrZero: ~

OpenEuropa\EPoetry\Request\Type\modifyRequestDetailsIn:
    properties:
        products:
            - Valid: ~
        contacts:
            - Valid: ~
            - NotNull: ~
        auxiliaryDocuments:
            - Valid: ~

OpenEuropa\EPoetry\Request\Type\modifyAuxiliaryDocumentsIn:
    properties:
        referenceDocuments:
            - Valid: ~
        traxDocuments:
            - Valid: ~
        spotDocument:
            - Valid: ~
        prtDocuments:
            - Valid: ~
