OpenEuropa\EPoetry\Request\Type\CreateLinguisticRequest:
    properties:
        requestDetails:
            - NotBlank: ~
        applicationName:
            - NotBlank: ~
        templateName:
            - NotBlank: ~
