name: ci
on: [push, pull_request]
jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION: ["8.1"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker-compose up -d
      - name: composer install
        run: docker-compose exec -T php composer install
      - name: phpunit
        run: docker-compose exec -T php ./vendor/bin/phpunit
  code-sniffer:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: "8.1"
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker-compose up -d
      - name: composer install
        run: docker-compose exec -T php composer install
      - name: grumphp
        run: docker-compose exec -T php ./vendor/bin/grumphp run
